#include "ite/itu.h"

extern void TouchCalibrationReset(void);
extern void ScreensaverReset(void);
extern void UpgradeReset(void);
extern void MainReset(void);
extern void LoginReset(void);
extern void MainMenuReset(void);
extern void PhoneReset(void);
extern void PhoneResidentReset(void);
extern void PhoneAdminReset(void);
extern void PhoneMiscReset(void);
extern void CallingReset(void);
extern void CalledReset(void);
extern void RedirectReset(void);
extern void RedirectResidentReset(void);
extern void RedirectAdminReset(void);
extern void RedirectMiscReset(void);
extern void CameraReset(void);
extern void CameraViewReset(void);
extern void GuardLogReset(void);
extern void GuardLogViewReset(void);
extern void SettingDisplayReset(void);
extern void SettingSoundReset(void);
extern void SettingVoiceReset(void);
extern void SettingNetworkReset(void);
extern void SettingLangReset(void);
extern void SettingTerminalReset(void);
extern void SettingDoorCameraReset(void);
extern void SettingMiscReset(void);
extern void SettingSysInfoReset(void);
extern void TimeReset(void);
extern void DateReset(void);
extern void AccountReset(void);
extern void AccountKeyboardReset(void);
extern void RecordReset(void);
extern void RecordViewReset(void);
extern void VideoMemoReset(void);
extern void CameraLobbyReset(void);

void resetScene(void)
{
	TouchCalibrationReset();
    ScreensaverReset();
    UpgradeReset();
    MainReset();
	LoginReset();
    MainMenuReset();
    PhoneReset();
    PhoneResidentReset();
    PhoneAdminReset();
    PhoneMiscReset();
    CallingReset();
    CalledReset();
    RedirectReset();
    RedirectResidentReset();
    RedirectAdminReset();
    RedirectMiscReset();
    CameraReset();
    CameraViewReset();
    GuardLogReset();
    GuardLogViewReset();
    SettingDisplayReset();
    SettingSoundReset();
    SettingVoiceReset();
    SettingNetworkReset();
    SettingLangReset();
    SettingTerminalReset();
    SettingDoorCameraReset();
    SettingMiscReset();
    SettingSysInfoReset();
    TimeReset();
    DateReset();
    AccountReset();
    AccountKeyboardReset();
    RecordReset();
    RecordViewReset();
    VideoMemoReset();
    CameraLobbyReset();
}
