add_executable(${CMAKE_PROJECT_NAME}
    layer_audioplayer.c
    layer_calendar.c
    layer_clock.c
    layer_imageplayer.c
    layer_imageview.c    
    layer_logo.c
    layer_main_menu.c
	layer_monitor.c
    layer_standby.c
    layer_videoplayer.c
    layer_videoview.c
    )
